Update CI pipeline

diff --git a/.github/workflows/build-and-test-app.yml b/.github/workflows/build-and-test-app.yml
--- a/.github/workflows/build-and-test-app.yml
+++ b/.github/workflows/build-and-test-app.yml
@@ -52,7 +52,7 @@ jobs:
       uses: docker/setup-buildx-action@v2
 
     - name: Set up Kind
-      uses: engineerd/setup-kind@v0.6.2
+      uses: engineerd/setup-kind@v0.8.0
       with:
         skipClusterCreation: true
     - name: Verify Kind installation
@@ -100,3 +100,10 @@ jobs:
       run: |
         kubectl port-forward svc/online-store 8000:80 >/tmp/port-forward.log 2>&1 &sleep 10
         curl --fail --retry 5 --retry-delay 3 http://localhost:8000/health
+      
+      # Clean up Cluster
+    - name: Tear down Kind Cluster
+      if: always()
+      run: |
+        # Delete cluster
+        kind delete cluster --name online-store || true
